// generated by stringer -type=AgariType; DO NOT EDIT

package agari

import "fmt"

const _AgariType_name = "NoneAgariShaboPenchanRyanmenKanchan"

var _AgariType_index = [...]uint8{0, 9, 14, 21, 28, 35}

func (i AgariType) String() string {
	if i < 0 || i+1 >= AgariType(len(_AgariType_index)) {
		return fmt.Sprintf("AgariType(%d)", i)
	}
	return _AgariType_name[_AgariType_index[i]:_AgariType_index[i+1]]
}
